import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: themeScript,
          }}
        />
      </head>
      <body
        className={`${inter.className} antialiased bg-gray-50 dark:bg-gray-900 scrollbar-light dark:scrollbar-dark`}
      >
        {children}
      </body>
    </html>
  );
}

const themeScript = `const theme = (() => {
				if (typeof localStorage !== 'undefined' && localStorage.getItem('theme')) {
					return localStorage.getItem('theme')
				}
				if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
					return 'dark'
				}
				return 'light'
			})()

			if (theme === 'light') {
				document.documentElement.classList.remove('dark')
			} else {
				document.documentElement.classList.add('dark')
			}
			window.localStorage.setItem('theme', theme)`;
